import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";

import { PeriodNav } from "@/components/period-nav";
import { Avatar, EmptyState } from "@/components/ui";
import { isManager, requireUser } from "@/lib/auth";
import { format, parseMonth } from "@/lib/dates";
import { db } from "@/lib/db";
import { formatCurrency } from "@/lib/salary";
import { RunPayrollForm } from "./run-payroll-form";

export const metadata: Metadata = { title: "Payroll" };

type Search = { month?: string };

export default async function PayrollPage({ searchParams }: { searchParams: Promise<Search> }) {
  const params = await searchParams;
  const user = await requireUser();

  return (
    <div className="flex flex-col gap-5">
      <div>
        <h1 className="text-xl font-semibold text-ink-900">Payroll</h1>
        <p className="text-sm text-ink-500">
          {isManager(user.role)
            ? "Run payroll for a month and review every payslip it produces."
            : "Your payslips, generated by HR at the end of each month."}
        </p>
      </div>

      {isManager(user.role) ? (
        <ManagerView params={params} companyId={user.companyId} />
      ) : (
        <MyPayslips employeeId={user.id} />
      )}
    </div>
  );
}

async function ManagerView({ params, companyId }: { params: Search; companyId: string }) {
  const month = parseMonth(params.month);
  const year = month.getFullYear();
  const monthNumber = month.getMonth() + 1;

  const employees = await db.employee.findMany({
    where: { companyId, status: "ACTIVE" },
    orderBy: { firstName: "asc" },
  });

  const payslips = await db.payslip.findMany({
    where: { periodYear: year, periodMonth: monthNumber, employee: { companyId } },
  });
  const byEmployee = new Map(payslips.map((p) => [p.employeeId, p]));

  const generatedCount = payslips.length;
  const totalNet = payslips.reduce((sum, p) => sum + p.netPay, 0);

  return (
    <>
      <div className="flex flex-wrap items-center justify-between gap-3">
        <Suspense fallback={<div className="h-9 w-48 rounded-md bg-ink-100" />}>
          <PeriodNav value={`${year}-${String(monthNumber).padStart(2, "0")}`} type="month" paramName="month" />
        </Suspense>
        <RunPayrollForm year={year} month={monthNumber} label={format(month, "MMMM yyyy")} />
      </div>

      <div className="grid gap-3 sm:grid-cols-3">
        <Stat label="Employees" value={String(employees.length)} />
        <Stat label="Payslips generated" value={`${generatedCount} / ${employees.length}`} tone={generatedCount === employees.length && employees.length > 0 ? "present" : undefined} />
        <Stat label="Total net pay" value={formatCurrency(totalNet)} />
      </div>

      {employees.length === 0 ? (
        <EmptyState title="No employees" description="Add employees before payroll can be run." />
      ) : (
        <div className="table-wrap">
          <table className="grid-table">
            <thead>
              <tr>
                <th>Employee</th>
                <th>Payable days</th>
                <th>Gross</th>
                <th>Deductions</th>
                <th>Net pay</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {employees.map((employee) => {
                const payslip = byEmployee.get(employee.id);
                return (
                  <tr key={employee.id}>
                    <td>
                      <Link href={`/employees/${employee.id}`} className="flex items-center gap-2.5 hover:text-brand-700">
                        <Avatar src={employee.avatar} name={`${employee.firstName} ${employee.lastName}`} size={28} />
                        <span>
                          <span className="block font-medium">
                            {employee.firstName} {employee.lastName}
                          </span>
                          <span className="mono block text-[11px] text-ink-400">{employee.loginId}</span>
                        </span>
                      </Link>
                    </td>
                    {payslip ? (
                      <>
                        <td className="num">
                          {payslip.payableDays} / {payslip.totalWorkingDays}
                        </td>
                        <td className="mono">{formatCurrency(payslip.grossMonthly)}</td>
                        <td className="mono text-danger">− {formatCurrency(payslip.totalDeductions)}</td>
                        <td className="mono font-semibold text-present">{formatCurrency(payslip.netPay)}</td>
                        <td>
                          <Link href={`/payroll/${payslip.id}`} className="text-sm font-medium text-brand-600 hover:underline">
                            View
                          </Link>
                        </td>
                      </>
                    ) : (
                      <td colSpan={4} className="text-sm text-ink-400">
                        Not yet generated
                      </td>
                    )}
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </>
  );
}

async function MyPayslips({ employeeId }: { employeeId: string }) {
  const payslips = await db.payslip.findMany({
    where: { employeeId },
    orderBy: [{ periodYear: "desc" }, { periodMonth: "desc" }],
  });

  if (payslips.length === 0) {
    return <EmptyState title="No payslips yet" description="Payslips appear here once HR runs payroll for a month you worked." />;
  }

  return (
    <div className="table-wrap">
      <table className="grid-table">
        <thead>
          <tr>
            <th>Period</th>
            <th>Payable days</th>
            <th>Gross</th>
            <th>Deductions</th>
            <th>Net pay</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {payslips.map((payslip) => (
            <tr key={payslip.id}>
              <td className="font-medium">{format(new Date(payslip.periodYear, payslip.periodMonth - 1, 1), "MMMM yyyy")}</td>
              <td className="num">
                {payslip.payableDays} / {payslip.totalWorkingDays}
              </td>
              <td className="mono">{formatCurrency(payslip.grossMonthly)}</td>
              <td className="mono text-danger">− {formatCurrency(payslip.totalDeductions)}</td>
              <td className="mono font-semibold text-present">{formatCurrency(payslip.netPay)}</td>
              <td>
                <Link href={`/payroll/${payslip.id}`} className="text-sm font-medium text-brand-600 hover:underline">
                  View
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: "present" }) {
  return (
    <div className="card px-4 py-3">
      <p className="label">{label}</p>
      <p className={`num mt-1 text-lg font-semibold ${tone === "present" ? "text-present" : "text-ink-900"}`}>{value}</p>
    </div>
  );
}
