import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";

import { PayrollLogo } from "@/components/brand-icons";
import { PeriodNav } from "@/components/period-nav";
import { Avatar, EmptyState } from "@/components/ui";
import { isManager, requireUser } from "@/lib/auth";
import { format, parseMonth } from "@/lib/dates";
import { db } from "@/lib/db";
import { formatCurrency } from "@/lib/salary";
import { PayrollTable } from "./payroll-table";
import { RunPayrollForm } from "./run-payroll-form";

export const metadata: Metadata = { title: "Payroll" };

type Search = { month?: string };

export default async function PayrollPage({ searchParams }: { searchParams: Promise<Search> }) {
  const params = await searchParams;
  const user = await requireUser();

  return (
    <div className="flex flex-col gap-5">
      {isManager(user.role) ? (
        <ManagerView params={params} companyId={user.companyId} />
      ) : (
        <MyPayslips employeeId={user.id} />
      )}
    </div>
  );
}

async function ManagerView({ params, companyId }: { params: Search; companyId: string }) {
  const month = parseMonth(params.month);
  const year = month.getFullYear();
  const monthNumber = month.getMonth() + 1;

  const employees = await db.employee.findMany({
    where: { companyId, status: "ACTIVE" },
    orderBy: { firstName: "asc" },
    select: {
      id: true,
      firstName: true,
      lastName: true,
      loginId: true,
      avatar: true,
      jobPosition: true,
      department: true,
      salary: {
        select: {
          monthlyWage: true,
          workingDaysPerWeek: true,
          breakHours: true,
          basicPercent: true,
          hraPercentOfBasic: true,
          standardAllowancePercent: true,
          performanceBonusPercent: true,
          ltaPercent: true,
          pfPercent: true,
          professionalTax: true,
        },
      },
    },
  });

  const payslips = await db.payslip.findMany({
    where: { periodYear: year, periodMonth: monthNumber, employee: { companyId } },
  });

  const generatedCount = payslips.length;
  const totalNet = payslips.reduce((sum, p) => sum + p.netPay, 0);

  return (
    <>
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div className="flex items-center gap-3">
          <PayrollLogo size={36} className="shrink-0" />
          <div>
            <h1 className="text-xl font-bold text-ink-900 tracking-tight">Payroll</h1>
            <p className="text-sm text-ink-500">
              Run payroll for a month and review every payslip it produces.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <Suspense fallback={<div className="h-9 w-48 rounded-md bg-ink-100" />}>
            <PeriodNav value={`${year}-${String(monthNumber).padStart(2, "0")}`} type="month" paramName="month" />
          </Suspense>
          <RunPayrollForm
            year={year}
            month={monthNumber}
            label={format(month, "MMMM yyyy")}
            employees={employees}
          />
        </div>
      </div>

      <div className="grid gap-3 sm:grid-cols-3">
        <Stat label="Employees" value={String(employees.length)} />
        <Stat label="Payslips generated" value={`${generatedCount} / ${employees.length}`} tone={generatedCount === employees.length && employees.length > 0 ? "present" : undefined} />
        <Stat label="Total net pay" value={formatCurrency(totalNet)} />
      </div>

      {employees.length === 0 ? (
        <EmptyState title="No employees" description="Add employees before payroll can be run." />
      ) : (
        <PayrollTable
          employees={employees}
          payslips={payslips}
          periodLabel={format(month, "MMMM yyyy")}
          year={year}
          month={monthNumber}
        />
      )}
    </>
  );
}

async function MyPayslips({ employeeId }: { employeeId: string }) {
  const payslips = await db.payslip.findMany({
    where: { employeeId },
    orderBy: [{ periodYear: "desc" }, { periodMonth: "desc" }],
  });

  return (
    <>
      <div className="flex items-center gap-3">
        <PayrollLogo size={36} className="shrink-0" />
        <div>
          <h1 className="text-xl font-bold text-ink-900 tracking-tight">Payroll</h1>
          <p className="text-sm text-ink-500">Your payslips, generated by HR at the end of each month.</p>
        </div>
      </div>

      {payslips.length === 0 ? (
        <EmptyState title="No payslips yet" description="Payslips appear here once HR runs payroll for a month you worked." />
      ) : (
        <div className="table-wrap">
          <table className="grid-table">
        <thead>
          <tr>
            <th>Period</th>
            <th>Payable days</th>
            <th>Gross</th>
            <th>Deductions</th>
            <th>Net pay</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {payslips.map((payslip) => (
            <tr key={payslip.id}>
              <td className="font-medium">{format(new Date(payslip.periodYear, payslip.periodMonth - 1, 1), "MMMM yyyy")}</td>
              <td className="num">
                {payslip.payableDays} / {payslip.totalWorkingDays}
              </td>
              <td className="mono">{formatCurrency(payslip.grossMonthly)}</td>
              <td className="mono text-ink-900">{formatCurrency(payslip.totalDeductions)}</td>
              <td className="mono font-semibold text-ink-900">{formatCurrency(payslip.netPay)}</td>
              <td>
                <Link href={`/payroll/${payslip.id}`} className="text-sm font-medium text-brand-600 hover:underline">
                  View
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
      )}
    </>
  );
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: "present" }) {
  return (
    <div className="card px-4 py-3">
      <p className="label">{label}</p>
      <p className={`num mt-1 text-lg font-semibold ${tone === "present" ? "text-present" : "text-ink-900"}`}>{value}</p>
    </div>
  );
}
